"""
KiMatch-relevant mock data — CEE companies in target industries.
Polish/Czech/Romanian/Slovak/Hungarian businesses that match KiMatch's ICP.
"""
import random
import hashlib
from typing import List


def generate_mock_signals(company_name: str) -> List[str]:
    """Generate deterministic mock growth signals based on company name hash (legacy)."""
    LEGACY_SIGNALS = [
        "hiring activity", "active LinkedIn presence", "founder posting",
        "expansion", "strong website presence", "recent leadership change",
        "new office location",
    ]
    seed = int(hashlib.md5(company_name.encode()).hexdigest()[:8], 16)
    rng = random.Random(seed)
    count = rng.randint(0, 3)
    return rng.sample(LEGACY_SIGNALS, min(count, len(LEGACY_SIGNALS)))


def get_mock_leads() -> List[dict]:
    """Generate ~30 KiMatch-relevant mock leads for CEE region."""
    leads = [
        # ============ POLAND ============
        {
            "company_name": "Markowski Logistyka",
            "website": "https://markowski-logistyka.pl",
            "country": "Poland",
            "industry": "Logistics",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/markowski-logistyka",
            "decision_maker_name": "Tomasz Markowski",
            "decision_maker_role": "Właściciel",
            "decision_maker_linkedin_url": "https://linkedin.com/in/tomaszmarkowski",
            "email": "t.markowski@markowski-logistyka.pl",
            "notes": "Founder-led logistics company, rapid expansion in 2023, no COO in place.",
            "source": "LinkedIn Search",
        },
        {
            "company_name": "Kowalski Budownictwo",
            "website": "https://kowalski-bud.pl",
            "country": "Poland",
            "industry": "Construction",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/kowalski-budownictwo",
            "decision_maker_name": "Krzysztof Kowalski",
            "decision_maker_role": "Prezes",
            "decision_maker_linkedin_url": "https://linkedin.com/in/krzysztofkowalski",
            "email": "k.kowalski@kowalski-bud.pl",
            "notes": "Fast-growing construction firm, won 3 major contracts in 2024, operations chaotic.",
            "source": "Industry Directory",
        },
        {
            "company_name": "FreshMart Polska",
            "website": "https://freshmart.pl",
            "country": "Poland",
            "industry": "FMCG",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/freshmart-polska",
            "decision_maker_name": "Agnieszka Wiśniewska",
            "decision_maker_role": "Prezes Zarządu",
            "decision_maker_linkedin_url": "https://linkedin.com/in/agnieszka-wisniewska",
            "email": "a.wisniewska@freshmart.pl",
            "notes": "Regional FMCG distributor expanding into 3 new voivodeships.",
            "source": "LinkedIn Search",
        },
        {
            "company_name": "TechPako Solutions",
            "website": "https://techpako.pl",
            "country": "Poland",
            "industry": "Manufacturing",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/techpako",
            "decision_maker_name": "Marek Zieliński",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/marekzielinski",
            "email": "m.zielinski@techpako.pl",
            "notes": "Packaging manufacturer scaling from regional to national. Hiring operations and HR roles.",
            "source": "Trade Show Contact",
        },
        {
            "company_name": "Wierzbicki Dystrybucja",
            "website": "https://wierzbicki.pl",
            "country": "Poland",
            "industry": "Distribution",
            "employee_range": "51-200",
            "linkedin_company_url": "",
            "decision_maker_name": "Paweł Wierzbicki",
            "decision_maker_role": "Właściciel",
            "decision_maker_linkedin_url": "",
            "email": "biuro@wierzbicki.pl",
            "notes": "Owner-operated distribution company, 65 employees, no formal HR or operations manager.",
            "source": "Cold Research",
        },
        {
            "company_name": "Sklep24 E-commerce",
            "website": "https://sklep24.pl",
            "country": "Poland",
            "industry": "E-commerce",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/sklep24",
            "decision_maker_name": "Rafał Nowak",
            "decision_maker_role": "Founder",
            "decision_maker_linkedin_url": "https://linkedin.com/in/rafalnowaklpl",
            "email": "r.nowak@sklep24.pl",
            "notes": "E-commerce retailer growing 80% YoY. Logistics and customer service overwhelmed.",
            "source": "LinkedIn Search",
        },
        {
            "company_name": "Piotrowska Serwis Sp. z o.o.",
            "website": "https://piotrowska-serwis.pl",
            "country": "Poland",
            "industry": "Professional Services",
            "employee_range": "20-50",
            "linkedin_company_url": "https://linkedin.com/company/piotrowska-serwis",
            "decision_maker_name": "Joanna Piotrowska",
            "decision_maker_role": "Dyrektor Zarządzający",
            "decision_maker_linkedin_url": "https://linkedin.com/in/joannapiotrowska",
            "email": "j.piotrowska@piotrowska-serwis.pl",
            "notes": "B2B services company growing from boutique to medium-size, needs structure.",
            "source": "Referral",
        },
        {
            "company_name": "Grupa Radwan Retail",
            "website": "https://radwan.pl",
            "country": "Poland",
            "industry": "Retail",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/radwan-retail",
            "decision_maker_name": "Bartosz Radwan",
            "decision_maker_role": "Prezes",
            "decision_maker_linkedin_url": "https://linkedin.com/in/bartoszradwan",
            "email": "b.radwan@radwan.pl",
            "notes": "Multi-location retail chain expanding from 8 to 20 stores. No COO.",
            "source": "LinkedIn Search",
        },
        {
            "company_name": "Adamczyk Transport",
            "website": "https://adamczyk-transport.pl",
            "country": "Poland",
            "industry": "Transportation",
            "employee_range": "51-200",
            "linkedin_company_url": "",
            "decision_maker_name": "Stanisław Adamczyk",
            "decision_maker_role": "Współwłaściciel",
            "decision_maker_linkedin_url": "",
            "email": "",
            "notes": "Road freight company, grown from 12 to 85 trucks in 4 years, management chaos.",
            "source": "Industry Directory",
        },
        {
            "company_name": "Zielona Dolina Foods",
            "website": "https://zielonadolina.pl",
            "country": "Poland",
            "industry": "Food & Beverage",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/zielona-dolina",
            "decision_maker_name": "Monika Lewandowska",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/monikalewandowska",
            "email": "m.lewandowska@zielonadolina.pl",
            "notes": "Food production company entering retail chains in Germany and Czech Republic.",
            "source": "Trade Show Contact",
        },

        # ============ CZECH REPUBLIC ============
        {
            "company_name": "Novák Stavby s.r.o.",
            "website": "https://novakstavby.cz",
            "country": "Czech Republic",
            "industry": "Construction",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/novak-stavby",
            "decision_maker_name": "Jiří Novák",
            "decision_maker_role": "Jednatel",
            "decision_maker_linkedin_url": "https://linkedin.com/in/jirinovákcz",
            "email": "j.novak@novakstavby.cz",
            "notes": "Czech construction company growing into Slovakia. Needs management infrastructure.",
            "source": "LinkedIn Search",
        },
        {
            "company_name": "ProLog Czech",
            "website": "https://prologczech.cz",
            "country": "Czech Republic",
            "industry": "Logistics",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/prolog-czech",
            "decision_maker_name": "Petr Dvořák",
            "decision_maker_role": "Managing Director",
            "decision_maker_linkedin_url": "https://linkedin.com/in/petrdvorak",
            "email": "p.dvorak@prologczech.cz",
            "notes": "E-fulfillment logistics company. Rapid headcount growth — from 90 to 230 in 18 months.",
            "source": "Cold Research",
        },
        {
            "company_name": "TopRetail CZ",
            "website": "https://topretail.cz",
            "country": "Czech Republic",
            "industry": "Retail",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/topretail-cz",
            "decision_maker_name": "Lukáš Procházka",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/lukasprochazkacz",
            "email": "l.procházka@topretail.cz",
            "notes": "Czech multi-brand retail, opening 15 new locations this year. Looking for operations roles.",
            "source": "Industry Directory",
        },

        # ============ ROMANIA ============
        {
            "company_name": "Ionescu Constructii",
            "website": "https://ionescu-constructii.ro",
            "country": "Romania",
            "industry": "Construction",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/ionescu-constructii",
            "decision_maker_name": "Alexandru Ionescu",
            "decision_maker_role": "Owner",
            "decision_maker_linkedin_url": "https://linkedin.com/in/alexandruionescu",
            "email": "a.ionescu@ionescu-constructii.ro",
            "notes": "Largest construction firm in Transylvania region. Owner-managed with 220 employees.",
            "source": "LinkedIn Search",
        },
        {
            "company_name": "FreshGo Distribution",
            "website": "https://freshgo.ro",
            "country": "Romania",
            "industry": "FMCG",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/freshgo-ro",
            "decision_maker_name": "Mihai Popescu",
            "decision_maker_role": "Founder",
            "decision_maker_linkedin_url": "https://linkedin.com/in/mihaipopescuro",
            "email": "m.popescu@freshgo.ro",
            "notes": "FMCG distribution startup turned mid-size — grew 3x in 2 years. No formal processes.",
            "source": "Cold Research",
        },
        {
            "company_name": "Carpathian Manufacturing",
            "website": "https://carpathian-mfg.ro",
            "country": "Romania",
            "industry": "Manufacturing",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/carpathian-manufacturing",
            "decision_maker_name": "Radu Constantin",
            "decision_maker_role": "General Manager",
            "decision_maker_linkedin_url": "https://linkedin.com/in/raduconstantin",
            "email": "r.constantin@carpathian-mfg.ro",
            "notes": "Metal components manufacturer supplying German auto brands. Scaling to meet demand.",
            "source": "Trade Show Contact",
        },

        # ============ HUNGARY ============
        {
            "company_name": "Magyar Logisztika Kft.",
            "website": "https://magyarlogisztika.hu",
            "country": "Hungary",
            "industry": "Logistics",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/magyar-logisztika",
            "decision_maker_name": "Gábor Kovács",
            "decision_maker_role": "Ügyvezető",
            "decision_maker_linkedin_url": "https://linkedin.com/in/gaborkovacs",
            "email": "g.kovacs@magyarlogisztika.hu",
            "notes": "Hungarian logistics SME, expanding across the Balkans. Hiring ops and HR managers.",
            "source": "LinkedIn Search",
        },
        {
            "company_name": "Pannonia Retail Group",
            "website": "https://pannonia-retail.hu",
            "country": "Hungary",
            "industry": "Retail",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/pannonia-retail",
            "decision_maker_name": "Éva Szabó",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/evaszbaho",
            "email": "e.szabo@pannonia-retail.hu",
            "notes": "Multi-category retail group. Recently acquired two smaller chains, integration challenges.",
            "source": "Cold Research",
        },

        # ============ SLOVAKIA ============
        {
            "company_name": "Slovak Build Group",
            "website": "https://slovakbuild.sk",
            "country": "Slovakia",
            "industry": "Construction",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/slovak-build",
            "decision_maker_name": "Martin Horváth",
            "decision_maker_role": "Owner",
            "decision_maker_linkedin_url": "",
            "email": "m.horvath@slovakbuild.sk",
            "notes": "Construction company, all operations run directly by founder. Turnover doubled in 2 years.",
            "source": "Industry Directory",
        },
        {
            "company_name": "EcoTrans Slovakia",
            "website": "https://ecotrans.sk",
            "country": "Slovakia",
            "industry": "Transportation",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/ecotrans-sk",
            "decision_maker_name": "Jana Kováčová",
            "decision_maker_role": "Managing Director",
            "decision_maker_linkedin_url": "https://linkedin.com/in/janakováčová",
            "email": "j.kovacova@ecotrans.sk",
            "notes": "Green transport startup now at 75 employees. Operations and HR becoming a bottleneck.",
            "source": "LinkedIn Search",
        },

        # ============ UKRAINE ============
        {
            "company_name": "Kyiv Packaging Ltd.",
            "website": "https://kyiv-pack.ua",
            "country": "Ukraine",
            "industry": "Manufacturing",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/kyiv-packaging",
            "decision_maker_name": "Oleksandr Kovalenko",
            "decision_maker_role": "Founder",
            "decision_maker_linkedin_url": "https://linkedin.com/in/oleksandrkovalenko",
            "email": "o.kovalenko@kyiv-pack.ua",
            "notes": "Packaging manufacturer expanding exports to Poland and Czechia. Needs structure for growth.",
            "source": "Trade Show Contact",
        },

        # ============ ADDITIONAL POLAND (high score leads) ============
        {
            "company_name": "Mazovia Wholesale",
            "website": "https://mazovia-wholesale.pl",
            "country": "Poland",
            "industry": "Wholesale",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/mazovia-wholesale",
            "decision_maker_name": "Piotr Bąk",
            "decision_maker_role": "Prezes",
            "decision_maker_linkedin_url": "https://linkedin.com/in/piotrbak",
            "email": "p.bak@mazovia-wholesale.pl",
            "notes": "Regional wholesale distributor, 320 employees, majority of management processes still in Excel.",
            "source": "LinkedIn Search",
        },
        {
            "company_name": "Kraków Tech Manufacturing",
            "website": "https://ktm-group.pl",
            "country": "Poland",
            "industry": "Manufacturing",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/krakow-tech-mfg",
            "decision_maker_name": "Wojciech Dąbrowski",
            "decision_maker_role": "Właściciel",
            "decision_maker_linkedin_url": "https://linkedin.com/in/wojciechdabrowski",
            "email": "w.dabrowski@ktm-group.pl",
            "notes": "Precision manufacturing. Founder managing 280 people without middle management layer.",
            "source": "Cold Research",
        },
        {
            "company_name": "PolStar E-Logistics",
            "website": "https://polstar.pl",
            "country": "Poland",
            "industry": "Logistics",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/polstar-logistics",
            "decision_maker_name": "Karolina Wróbel",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/karolinawrobel",
            "email": "k.wrobel@polstar.pl",
            "notes": "Last-mile delivery company. Doubled headcount in 12 months. Processes not keeping up.",
            "source": "LinkedIn Search",
        },
        {
            "company_name": "Gdańsk Business Services",
            "website": "https://gbs-group.pl",
            "country": "Poland",
            "industry": "Business Services",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/gbs-group",
            "decision_maker_name": "Michał Szymański",
            "decision_maker_role": "Founding Partner",
            "decision_maker_linkedin_url": "https://linkedin.com/in/michaelszymanski",
            "email": "m.szymanski@gbs-group.pl",
            "notes": "Shared services firm, recently crossed 100 employees. Partnership disputes on direction.",
            "source": "Industry Directory",
        },
        {
            "company_name": "WarszawaNet Retail",
            "website": "https://warszawanet.pl",
            "country": "Poland",
            "industry": "Retail",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/warszawanet",
            "decision_maker_name": "Aleksandra Kamińska",
            "decision_maker_role": "Dyrektor Generalny",
            "decision_maker_linkedin_url": "https://linkedin.com/in/aleksandrakaminska",
            "email": "a.kaminska@warszawanet.pl",
            "notes": "Omnichannel retail, combining online and offline. Rapid team growth causing coordination issues.",
            "source": "LinkedIn Search",
        },
        # ============ WEAK LEADS (TO DEMONSTRATE FILTERING) ============
        {
            "company_name": "Berlin Logistics Group",
            "website": "https://berlin-logistics.de",
            "country": "Germany",
            "industry": "Logistics",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/berlin-logistics",
            "decision_maker_name": "Hans Mueller",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/hansmueller",
            "email": "h.mueller@berlin-logistics.de",
            "notes": "Strong scaling but wrong country (Germany).",
            "source": "Inbound List",
        },
        {
            "company_name": "Warsaw Code Startup",
            "website": "https://waw-code.pl",
            "country": "Poland",
            "industry": "Professional Services",
            "employee_range": "1-10",
            "linkedin_company_url": "https://linkedin.com/company/waw-code",
            "decision_maker_name": "Jan Kowalski",
            "decision_maker_role": "Właściciel",
            "decision_maker_linkedin_url": "https://linkedin.com/in/jankowalski-code",
            "email": "jan@waw-code.pl",
            "notes": "Too small, only 6 employees. Not ready for structural consulting.",
            "source": "Startup Directory",
        },
        {
            "company_name": "Krakow Budownictwo Marketing",
            "website": "https://krak-bud.pl",
            "country": "Poland",
            "industry": "Construction",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/krak-bud",
            "decision_maker_name": "Anna Nowak",
            "decision_maker_role": "Marketing Manager",
            "decision_maker_linkedin_url": "https://linkedin.com/in/annanowak-marketing",
            "email": "anna.nowak@krak-bud.pl",
            "notes": "Right size and industry, but wrong decision maker role.",
            "source": "Marketing Conference",
        },
        {
            "company_name": "Quiet Polish Retailer",
            "website": "",
            "country": "Poland",
            "industry": "Retail",
            "employee_range": "201-500",
            "linkedin_company_url": "",
            "decision_maker_name": "Michal Wisniewski",
            "decision_maker_role": "Dyrektor Generalny",
            "decision_maker_linkedin_url": "",
            "email": "",
            "notes": "No email, no website, no signals detected. Invisible online.",
            "source": "Old Database",
        },
        {
            "company_name": "Vegas Casino Central Europe",
            "website": "https://vegas-cee.com",
            "country": "Czech Republic",
            "industry": "Gambling",
            "employee_range": "500-1000",
            "linkedin_company_url": "https://linkedin.com/company/vegas-cee",
            "decision_maker_name": "Pavel Dvorak",
            "decision_maker_role": "Jednatel",
            "decision_maker_linkedin_url": "https://linkedin.com/in/paveldvorak",
            "email": "p.dvorak@vegas-cee.com",
            "notes": "Excluded industry (Gambling).",
            "source": "Database Purchase",
        },
    ]

    # Add legacy signals for backward compat
    for lead in leads:
        if not lead.get("growth_signals"):
            lead["growth_signals"] = generate_mock_signals(lead["company_name"])

    return leads
