"""
QMatch-relevant mock data — CEE companies in target industries.
Updated with all new ABM spec fields: revenue, growth %, years in market,
legal form, company description, and distributed across all 3 target groups.

Group 1 — Rapid Growth: revenue 20–100M PLN, growth >= 50%, years <= 15
Group 2 — Transformation: revenue 20–150M PLN, growth 0–20%, years 15–25
Group 3 — Declining Revenue: revenue 20–150M PLN, growth < 0, years >= 20
"""
import random
import hashlib
from typing import List


def generate_mock_signals(company_name: str) -> List[str]:
    """Generate deterministic mock growth signals based on company name hash (legacy)."""
    LEGACY_SIGNALS = [
        "hiring activity", "active LinkedIn presence", "founder posting",
        "expansion", "strong website presence", "recent leadership change",
        "new office location",
    ]
    seed = int(hashlib.md5(company_name.encode()).hexdigest()[:8], 16)
    rng = random.Random(seed)
    count = rng.randint(0, 3)
    return rng.sample(LEGACY_SIGNALS, min(count, len(LEGACY_SIGNALS)))


def get_mock_leads() -> List[dict]:
    """Generate ~33 QMatch-relevant mock leads distributed across 3 target groups."""
    leads = [

        # ================================================================
        # GROUP 1 — RAPID GROWTH PHASE (growth >= 50%, years <= 15)
        # ================================================================

        {
            "company_name": "Markowski Logistyka",
            "website": "https://markowski-logistyka.pl",
            "country": "Poland",
            "industry": "Logistics",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/markowski-logistyka",
            "decision_maker_name": "Tomasz Markowski",
            "decision_maker_role": "Właściciel",
            "decision_maker_linkedin_url": "https://linkedin.com/in/tomaszmarkowski",
            "email": "t.markowski@markowski-logistyka.pl",
            "notes": "Founder-led logistics company, rapid expansion in 2023, no COO in place.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 42M",
            "revenue_growth_pct": 78.0,
            "revenue_trend": "growing",
            "years_in_market": 8,
            "legal_form": "Sp. z o.o.",
            "company_description": "Regional road freight company specializing in last-mile distribution across Mazowieckie and Łódź voivodeships.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Sklep24 E-commerce",
            "website": "https://sklep24.pl",
            "country": "Poland",
            "industry": "E-commerce",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/sklep24",
            "decision_maker_name": "Rafał Nowak",
            "decision_maker_role": "Founder",
            "decision_maker_linkedin_url": "https://linkedin.com/in/rafalnowaklpl",
            "email": "r.nowak@sklep24.pl",
            "notes": "E-commerce retailer growing 80% YoY. Logistics and customer service overwhelmed.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 31M",
            "revenue_growth_pct": 83.0,
            "revenue_trend": "growing",
            "years_in_market": 6,
            "legal_form": "Sp. z o.o.",
            "company_description": "Online multi-category retailer selling electronics, household goods and fashion; fulfils 3,000+ orders per day.",
            "ownership_structure": "Founder-managed",
        },
        {
            "company_name": "PolStar E-Logistics",
            "website": "https://polstar.pl",
            "country": "Poland",
            "industry": "Logistics",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/polstar-logistics",
            "decision_maker_name": "Karolina Wróbel",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/karolinawrobel",
            "email": "k.wrobel@polstar.pl",
            "notes": "Last-mile delivery company. Doubled headcount in 12 months. Processes not keeping up.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 27M",
            "revenue_growth_pct": 112.0,
            "revenue_trend": "growing",
            "years_in_market": 5,
            "legal_form": "Sp. z o.o.",
            "company_description": "Urban last-mile delivery operator serving e-commerce platforms across Warsaw, Kraków and Wrocław.",
            "ownership_structure": "Founder-managed",
        },
        {
            "company_name": "TechPako Solutions",
            "website": "https://techpako.pl",
            "country": "Poland",
            "industry": "Manufacturing",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/techpako",
            "decision_maker_name": "Marek Zieliński",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/marekzielinski",
            "email": "m.zielinski@techpako.pl",
            "notes": "Packaging manufacturer scaling from regional to national. Hiring operations and HR roles.",
            "source": "Trade Show Contact",
            # ABM fields
            "annual_revenue_pln": "PLN 68M",
            "revenue_growth_pct": 65.0,
            "revenue_trend": "growing",
            "years_in_market": 11,
            "legal_form": "Sp. z o.o.",
            "company_description": "Industrial packaging manufacturer producing corrugated cardboard and protective foam solutions for FMCG and automotive sectors.",
            "ownership_structure": "Founder-managed",
        },
        {
            "company_name": "FreshMart Polska",
            "website": "https://freshmart.pl",
            "country": "Poland",
            "industry": "FMCG",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/freshmart-polska",
            "decision_maker_name": "Agnieszka Wiśniewska",
            "decision_maker_role": "Prezes Zarządu",
            "decision_maker_linkedin_url": "https://linkedin.com/in/agnieszka-wisniewska",
            "email": "a.wisniewska@freshmart.pl",
            "notes": "Regional FMCG distributor expanding into 3 new voivodeships.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 38M",
            "revenue_growth_pct": 55.0,
            "revenue_trend": "growing",
            "years_in_market": 9,
            "legal_form": "Sp. z o.o.",
            "company_description": "FMCG wholesale distributor supplying grocery chains and independent shops across southern and central Poland.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Wierzbicki Dystrybucja",
            "website": "https://wierzbicki.pl",
            "country": "Poland",
            "industry": "Distribution",
            "employee_range": "51-200",
            "linkedin_company_url": "",
            "decision_maker_name": "Paweł Wierzbicki",
            "decision_maker_role": "Właściciel",
            "decision_maker_linkedin_url": "",
            "email": "biuro@wierzbicki.pl",
            "notes": "Owner-operated distribution company, 65 employees, no formal HR or operations manager.",
            "source": "Cold Research",
            # ABM fields
            "annual_revenue_pln": "PLN 24M",
            "revenue_growth_pct": 58.0,
            "revenue_trend": "growing",
            "years_in_market": 10,
            "legal_form": "Sp. z o.o.",
            "company_description": "Food ingredients distributor supplying bakeries and confectionery manufacturers nationwide.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "FreshGo Distribution",
            "website": "https://freshgo.ro",
            "country": "Romania",
            "industry": "FMCG",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/freshgo-ro",
            "decision_maker_name": "Mihai Popescu",
            "decision_maker_role": "Founder",
            "decision_maker_linkedin_url": "https://linkedin.com/in/mihaipopescuro",
            "email": "m.popescu@freshgo.ro",
            "notes": "FMCG distribution startup turned mid-size — grew 3x in 2 years. No formal processes.",
            "source": "Cold Research",
            # ABM fields
            "annual_revenue_pln": "PLN 29M",
            "revenue_growth_pct": 95.0,
            "revenue_trend": "growing",
            "years_in_market": 7,
            "legal_form": "SRL",
            "company_description": "Fast-moving consumer goods distributor covering Bucharest metro area and Transylvania region.",
            "ownership_structure": "Founder-managed",
        },
        {
            "company_name": "EcoTrans Slovakia",
            "website": "https://ecotrans.sk",
            "country": "Slovakia",
            "industry": "Transportation",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/ecotrans-sk",
            "decision_maker_name": "Jana Kováčová",
            "decision_maker_role": "Managing Director",
            "decision_maker_linkedin_url": "https://linkedin.com/in/janakováčová",
            "email": "j.kovacova@ecotrans.sk",
            "notes": "Green transport startup now at 75 employees. Operations and HR becoming a bottleneck.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 22M",
            "revenue_growth_pct": 72.0,
            "revenue_trend": "growing",
            "years_in_market": 6,
            "legal_form": "s.r.o.",
            "company_description": "Eco-friendly B2B transport company operating electric and CNG fleet across Slovakia and Austria.",
            "ownership_structure": "Founder-managed",
        },
        {
            "company_name": "Novák Stavby s.r.o.",
            "website": "https://novakstavby.cz",
            "country": "Czech Republic",
            "industry": "Construction",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/novak-stavby",
            "decision_maker_name": "Jiří Novák",
            "decision_maker_role": "Jednatel",
            "decision_maker_linkedin_url": "https://linkedin.com/in/jirinovákcz",
            "email": "j.novak@novakstavby.cz",
            "notes": "Czech construction company growing into Slovakia. Needs management infrastructure.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 45M",
            "revenue_growth_pct": 61.0,
            "revenue_trend": "growing",
            "years_in_market": 12,
            "legal_form": "s.r.o.",
            "company_description": "General contractor specializing in residential and light commercial construction across Moravia and Western Slovakia.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Kyiv Packaging Ltd.",
            "website": "https://kyiv-pack.ua",
            "country": "Ukraine",
            "industry": "Manufacturing",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/kyiv-packaging",
            "decision_maker_name": "Oleksandr Kovalenko",
            "decision_maker_role": "Founder",
            "decision_maker_linkedin_url": "https://linkedin.com/in/oleksandrkovalenko",
            "email": "o.kovalenko@kyiv-pack.ua",
            "notes": "Packaging manufacturer expanding exports to Poland and Czechia. Needs structure for growth.",
            "source": "Trade Show Contact",
            # ABM fields
            "annual_revenue_pln": "PLN 33M",
            "revenue_growth_pct": 53.0,
            "revenue_trend": "growing",
            "years_in_market": 10,
            "legal_form": "TOV",
            "company_description": "Flexible packaging manufacturer producing bags, pouches and wrapping materials for food and pharmaceutical industries.",
            "ownership_structure": "Founder-managed",
        },

        # ================================================================
        # GROUP 2 — TRANSFORMATION POTENTIAL (growth 0–20%, years 15–25)
        # ================================================================

        {
            "company_name": "Kowalski Budownictwo",
            "website": "https://kowalski-bud.pl",
            "country": "Poland",
            "industry": "Construction",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/kowalski-budownictwo",
            "decision_maker_name": "Krzysztof Kowalski",
            "decision_maker_role": "Prezes",
            "decision_maker_linkedin_url": "https://linkedin.com/in/krzysztofkowalski",
            "email": "k.kowalski@kowalski-bud.pl",
            "notes": "Fast-growing construction firm, won 3 major contracts in 2024, operations chaotic.",
            "source": "Industry Directory",
            # ABM fields
            "annual_revenue_pln": "PLN 95M",
            "revenue_growth_pct": 12.0,
            "revenue_trend": "stable",
            "years_in_market": 19,
            "legal_form": "Sp. z o.o.",
            "company_description": "Mid-size general contractor delivering infrastructure and industrial construction projects across central and southern Poland.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Mazovia Wholesale",
            "website": "https://mazovia-wholesale.pl",
            "country": "Poland",
            "industry": "Wholesale",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/mazovia-wholesale",
            "decision_maker_name": "Piotr Bąk",
            "decision_maker_role": "Prezes",
            "decision_maker_linkedin_url": "https://linkedin.com/in/piotrbak",
            "email": "p.bak@mazovia-wholesale.pl",
            "notes": "Regional wholesale distributor, 320 employees, majority of management processes still in Excel.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 120M",
            "revenue_growth_pct": 8.0,
            "revenue_trend": "stable",
            "years_in_market": 22,
            "legal_form": "Sp. z o.o.",
            "company_description": "Building materials wholesaler supplying construction companies and hardware stores across the Mazowia region.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Kraków Tech Manufacturing",
            "website": "https://ktm-group.pl",
            "country": "Poland",
            "industry": "Manufacturing",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/krakow-tech-mfg",
            "decision_maker_name": "Wojciech Dąbrowski",
            "decision_maker_role": "Właściciel",
            "decision_maker_linkedin_url": "https://linkedin.com/in/wojciechdabrowski",
            "email": "w.dabrowski@ktm-group.pl",
            "notes": "Precision manufacturing. Founder managing 280 people without middle management layer.",
            "source": "Cold Research",
            # ABM fields
            "annual_revenue_pln": "PLN 88M",
            "revenue_growth_pct": 6.0,
            "revenue_trend": "stable",
            "years_in_market": 24,
            "legal_form": "Sp. z o.o.",
            "company_description": "Precision metal component manufacturer supplying automotive and aerospace OEMs; holds ISO 9001 and IATF 16949 certifications.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Piotrowska Serwis Sp. z o.o.",
            "website": "https://piotrowska-serwis.pl",
            "country": "Poland",
            "industry": "Professional Services",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/piotrowska-serwis",
            "decision_maker_name": "Joanna Piotrowska",
            "decision_maker_role": "Dyrektor Zarządzający",
            "decision_maker_linkedin_url": "https://linkedin.com/in/joannapiotrowska",
            "email": "j.piotrowska@piotrowska-serwis.pl",
            "notes": "B2B services company growing from boutique to medium-size, needs structure.",
            "source": "Referral",
            # ABM fields
            "annual_revenue_pln": "PLN 28M",
            "revenue_growth_pct": 15.0,
            "revenue_trend": "stable",
            "years_in_market": 17,
            "legal_form": "Sp. z o.o.",
            "company_description": "B2B facility management company providing cleaning, security and maintenance services to office parks and retail chains.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Gdańsk Business Services",
            "website": "https://gbs-group.pl",
            "country": "Poland",
            "industry": "Business Services",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/gbs-group",
            "decision_maker_name": "Michał Szymański",
            "decision_maker_role": "Founding Partner",
            "decision_maker_linkedin_url": "https://linkedin.com/in/michaelszymanski",
            "email": "m.szymanski@gbs-group.pl",
            "notes": "Shared services firm, recently crossed 100 employees. Partnership disputes on direction.",
            "source": "Industry Directory",
            # ABM fields
            "annual_revenue_pln": "PLN 35M",
            "revenue_growth_pct": 18.0,
            "revenue_trend": "stable",
            "years_in_market": 16,
            "legal_form": "Sp. z o.o.",
            "company_description": "Business process outsourcing firm offering accounting, HR administration and payroll services to SME clients.",
            "ownership_structure": "Partner-managed",
        },
        {
            "company_name": "Carpathian Manufacturing",
            "website": "https://carpathian-mfg.ro",
            "country": "Romania",
            "industry": "Manufacturing",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/carpathian-manufacturing",
            "decision_maker_name": "Radu Constantin",
            "decision_maker_role": "General Manager",
            "decision_maker_linkedin_url": "https://linkedin.com/in/raduconstantin",
            "email": "r.constantin@carpathian-mfg.ro",
            "notes": "Metal components manufacturer supplying German auto brands. Scaling to meet demand.",
            "source": "Trade Show Contact",
            # ABM fields
            "annual_revenue_pln": "PLN 110M",
            "revenue_growth_pct": 9.0,
            "revenue_trend": "stable",
            "years_in_market": 20,
            "legal_form": "SRL",
            "company_description": "Stamped and machined metal components manufacturer; main customers include Tier 1 automotive suppliers to BMW and VW.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "ProLog Czech",
            "website": "https://prologczech.cz",
            "country": "Czech Republic",
            "industry": "Logistics",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/prolog-czech",
            "decision_maker_name": "Petr Dvořák",
            "decision_maker_role": "Managing Director",
            "decision_maker_linkedin_url": "https://linkedin.com/in/petrdvorak",
            "email": "p.dvorak@prologczech.cz",
            "notes": "E-fulfillment logistics company. Rapid headcount growth — from 90 to 230 in 18 months.",
            "source": "Cold Research",
            # ABM fields
            "annual_revenue_pln": "PLN 75M",
            "revenue_growth_pct": 14.0,
            "revenue_trend": "stable",
            "years_in_market": 18,
            "legal_form": "s.r.o.",
            "company_description": "E-commerce fulfilment and warehousing operator running 4 logistics centres across Czechia and Slovakia.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Magyar Logisztika Kft.",
            "website": "https://magyarlogisztika.hu",
            "country": "Hungary",
            "industry": "Logistics",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/magyar-logisztika",
            "decision_maker_name": "Gábor Kovács",
            "decision_maker_role": "Ügyvezető",
            "decision_maker_linkedin_url": "https://linkedin.com/in/gaborkovacs",
            "email": "g.kovacs@magyarlogisztika.hu",
            "notes": "Hungarian logistics SME, expanding across the Balkans. Hiring ops and HR managers.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 40M",
            "revenue_growth_pct": 11.0,
            "revenue_trend": "stable",
            "years_in_market": 21,
            "legal_form": "Kft.",
            "company_description": "Road freight and cross-docking operator connecting Hungarian manufacturers with Balkan distribution networks.",
            "ownership_structure": "Owner-managed",
        },

        # ================================================================
        # GROUP 3 — DECLINING REVENUE (growth < 0, years >= 20)
        # ================================================================

        {
            "company_name": "Grupa Radwan Retail",
            "website": "https://radwan.pl",
            "country": "Poland",
            "industry": "Retail",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/radwan-retail",
            "decision_maker_name": "Bartosz Radwan",
            "decision_maker_role": "Prezes",
            "decision_maker_linkedin_url": "https://linkedin.com/in/bartoszradwan",
            "email": "b.radwan@radwan.pl",
            "notes": "Multi-location retail chain. Revenue declined for 2nd consecutive year. No digital strategy.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 105M",
            "revenue_growth_pct": -14.0,
            "revenue_trend": "declining",
            "years_in_market": 27,
            "legal_form": "Sp. z o.o.",
            "company_description": "Household goods and DIY retailer with 22 stores across Małopolska and Podkarpacie; owner founded the chain in 1998.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Adamczyk Transport",
            "website": "https://adamczyk-transport.pl",
            "country": "Poland",
            "industry": "Transportation",
            "employee_range": "51-200",
            "linkedin_company_url": "",
            "decision_maker_name": "Stanisław Adamczyk",
            "decision_maker_role": "Współwłaściciel",
            "decision_maker_linkedin_url": "",
            "email": "",
            "notes": "Road freight company. Revenue dropped 18% YoY after losing 2 key contracts. Owner managing all personally.",
            "source": "Industry Directory",
            # ABM fields
            "annual_revenue_pln": "PLN 52M",
            "revenue_growth_pct": -18.0,
            "revenue_trend": "declining",
            "years_in_market": 25,
            "legal_form": "Sp. z o.o.",
            "company_description": "Road freight carrier running 85 trucks for retail chains and food producers across Poland and Germany.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Zielona Dolina Foods",
            "website": "https://zielonadolina.pl",
            "country": "Poland",
            "industry": "Food & Beverage",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/zielona-dolina",
            "decision_maker_name": "Monika Lewandowska",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/monikalewandowska",
            "email": "m.lewandowska@zielonadolina.pl",
            "notes": "Food production company. Revenue fell for 2nd year running after losing German export contract.",
            "source": "Trade Show Contact",
            # ABM fields
            "annual_revenue_pln": "PLN 77M",
            "revenue_growth_pct": -11.0,
            "revenue_trend": "declining",
            "years_in_market": 30,
            "legal_form": "Sp. z o.o.",
            "company_description": "Family-owned food manufacturer producing dairy and chilled ready-meals sold under private labels for supermarket chains.",
            "ownership_structure": "Family business, founder's daughter is CEO",
        },
        {
            "company_name": "WarszawaNet Retail",
            "website": "https://warszawanet.pl",
            "country": "Poland",
            "industry": "Retail",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/warszawanet",
            "decision_maker_name": "Aleksandra Kamińska",
            "decision_maker_role": "Dyrektor Generalny",
            "decision_maker_linkedin_url": "https://linkedin.com/in/aleksandrakaminska",
            "email": "a.kaminska@warszawanet.pl",
            "notes": "Omnichannel retail. Revenue declined 9% YoY as foot traffic to their stores drops persistently.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 48M",
            "revenue_growth_pct": -9.0,
            "revenue_trend": "declining",
            "years_in_market": 22,
            "legal_form": "Sp. z o.o.",
            "company_description": "Electronics and telecom accessories retailer operating 18 physical outlets and an online store, heavily dependent on shopping centre traffic.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Ionescu Constructii",
            "website": "https://ionescu-constructii.ro",
            "country": "Romania",
            "industry": "Construction",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/ionescu-constructii",
            "decision_maker_name": "Alexandru Ionescu",
            "decision_maker_role": "Owner",
            "decision_maker_linkedin_url": "https://linkedin.com/in/alexandruionescu",
            "email": "a.ionescu@ionescu-constructii.ro",
            "notes": "Largest construction firm in Transylvania region. Revenue declined 2 years in row due to public contract loss.",
            "source": "LinkedIn Search",
            # ABM fields
            "annual_revenue_pln": "PLN 130M",
            "revenue_growth_pct": -7.0,
            "revenue_trend": "declining",
            "years_in_market": 28,
            "legal_form": "SRL",
            "company_description": "Civil engineering and infrastructure contractor operating across Transylvania; historically reliant on EU-funded public tenders.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Slovak Build Group",
            "website": "https://slovakbuild.sk",
            "country": "Slovakia",
            "industry": "Construction",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/slovak-build",
            "decision_maker_name": "Martin Horváth",
            "decision_maker_role": "Owner",
            "decision_maker_linkedin_url": "",
            "email": "m.horvath@slovakbuild.sk",
            "notes": "Construction company. Revenue fell 22% in last 2 years. Founder running everything.",
            "source": "Industry Directory",
            # ABM fields
            "annual_revenue_pln": "PLN 41M",
            "revenue_growth_pct": -22.0,
            "revenue_trend": "declining",
            "years_in_market": 26,
            "legal_form": "s.r.o.",
            "company_description": "Residential and commercial construction firm operating across western Slovakia; specialises in modular construction.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Pannonia Retail Group",
            "website": "https://pannonia-retail.hu",
            "country": "Hungary",
            "industry": "Retail",
            "employee_range": "201-500",
            "linkedin_company_url": "https://linkedin.com/company/pannonia-retail",
            "decision_maker_name": "Éva Szabó",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/evaszbaho",
            "email": "e.szabo@pannonia-retail.hu",
            "notes": "Multi-category retail group. Revenue declined for 2nd consecutive year. Integration issues after acquisition.",
            "source": "Cold Research",
            # ABM fields
            "annual_revenue_pln": "PLN 145M",
            "revenue_growth_pct": -8.0,
            "revenue_trend": "declining",
            "years_in_market": 24,
            "legal_form": "Kft.",
            "company_description": "Multi-brand fashion, home and electronics retail group operating 40+ stores across Hungary and Romania.",
            "ownership_structure": "Owner-managed",
        },

        # ================================================================
        # WEAK LEADS / EDGE CASES (demonstrate filtering)
        # ================================================================

        {
            "company_name": "Berlin Logistics Group",
            "website": "https://berlin-logistics.de",
            "country": "Germany",
            "industry": "Logistics",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/berlin-logistics",
            "decision_maker_name": "Hans Mueller",
            "decision_maker_role": "CEO",
            "decision_maker_linkedin_url": "https://linkedin.com/in/hansmueller",
            "email": "h.mueller@berlin-logistics.de",
            "notes": "Strong scaling but wrong country (Germany). Outside CEE core target.",
            "source": "Inbound List",
            "annual_revenue_pln": "PLN 60M",
            "revenue_growth_pct": 40.0,
            "revenue_trend": "growing",
            "years_in_market": 12,
            "legal_form": "GmbH",
            "company_description": "Regional logistics company providing warehousing and LTL shipping across Germany and Poland.",
            "ownership_structure": "Owner-managed",
        },
        {
            "company_name": "Warsaw Code Startup",
            "website": "https://waw-code.pl",
            "country": "Poland",
            "industry": "Professional Services",
            "employee_range": "1-10",
            "linkedin_company_url": "https://linkedin.com/company/waw-code",
            "decision_maker_name": "Jan Kowalski",
            "decision_maker_role": "Właściciel",
            "decision_maker_linkedin_url": "https://linkedin.com/in/jankowalski-code",
            "email": "jan@waw-code.pl",
            "notes": "Too small, only 6 employees. Not ready for structural consulting.",
            "source": "Startup Directory",
            "annual_revenue_pln": "PLN 1.2M",
            "revenue_growth_pct": 30.0,
            "revenue_trend": "growing",
            "years_in_market": 3,
            "legal_form": "Sp. z o.o.",
            "company_description": "Software development shop building custom CRM systems for SMEs.",
            "ownership_structure": "Founder-managed",
        },
        {
            "company_name": "Krakow Budownictwo Marketing",
            "website": "https://krak-bud.pl",
            "country": "Poland",
            "industry": "Construction",
            "employee_range": "51-200",
            "linkedin_company_url": "https://linkedin.com/company/krak-bud",
            "decision_maker_name": "Anna Nowak",
            "decision_maker_role": "Marketing Manager",
            "decision_maker_linkedin_url": "https://linkedin.com/in/annanowak-marketing",
            "email": "anna.nowak@krak-bud.pl",
            "notes": "Right size and industry, but wrong decision maker role (Marketing Manager, not owner/CEO).",
            "source": "Marketing Conference",
            "annual_revenue_pln": "PLN 55M",
            "revenue_growth_pct": 5.0,
            "revenue_trend": "stable",
            "years_in_market": 15,
            "legal_form": "Sp. z o.o.",
            "company_description": "Construction company specialising in commercial fit-outs and renovation projects.",
            "ownership_structure": "Unknown",
        },
        {
            "company_name": "Quiet Polish Retailer",
            "website": "",
            "country": "Poland",
            "industry": "Retail",
            "employee_range": "201-500",
            "linkedin_company_url": "",
            "decision_maker_name": "Michal Wisniewski",
            "decision_maker_role": "Dyrektor Generalny",
            "decision_maker_linkedin_url": "",
            "email": "",
            "notes": "No email, no website, no signals detected. Invisible online.",
            "source": "Old Database",
            "annual_revenue_pln": "",
            "revenue_growth_pct": None,
            "revenue_trend": "",
            "years_in_market": None,
            "legal_form": "Sp. z o.o.",
            "company_description": "",
            "ownership_structure": "Unknown",
        },
        {
            "company_name": "Vegas Casino Central Europe",
            "website": "https://vegas-cee.com",
            "country": "Czech Republic",
            "industry": "Gambling",
            "employee_range": "500-1000",
            "linkedin_company_url": "https://linkedin.com/company/vegas-cee",
            "decision_maker_name": "Pavel Dvorak",
            "decision_maker_role": "Jednatel",
            "decision_maker_linkedin_url": "https://linkedin.com/in/paveldvorak",
            "email": "p.dvorak@vegas-cee.com",
            "notes": "Excluded industry (Gambling).",
            "source": "Database Purchase",
            "annual_revenue_pln": "PLN 200M",
            "revenue_growth_pct": 5.0,
            "revenue_trend": "stable",
            "years_in_market": 18,
            "legal_form": "s.r.o.",
            "company_description": "Casino and gaming operator running 12 venues across Czech Republic and Slovakia.",
            "ownership_structure": "Corporate-owned",
        },
    ]

    # Add legacy signals for backward compat
    for lead in leads:
        if not lead.get("growth_signals"):
            lead["growth_signals"] = generate_mock_signals(lead["company_name"])

    return leads
